### ISSUE TITLE
跟着视频弄的，不行，看起来是正则的问题？

### ISSUE THREAD

**Issue by skyhhjmk** [2331892928/AMEN-GoEdge-User_backEnd#5]
```
[2023-11-18 09:35:10 +0000] [15834] [INFO] Starting gunicorn 21.2.0
[2023-11-18 09:35:10 +0000] [15834] [INFO] Listening at: http://0.0.0.0:80 (15834)
[2023-11-18 09:35:10 +0000] [15834] [INFO] Using worker: geventwebsocket.gunicorn.workers.GeventWebSocketWorker
[2023-11-18 09:35:10 +0000] [15842] [INFO] Booting worker with pid: 15842
[2023-11-18 09:35:11 +0000] [15842] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/www/wwwroot/AMEN-GoEdge-User_backEnd-master/af051c89597cd018ce51bd8fd53014ff_venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/www/wwwroot/AMEN-GoEdge-User_backEnd-master/af051c89597cd018ce51bd8fd53014ff_venv/lib/python3.7/site-packages/gunicorn/workers/ggevent.py", line 147, in init_process
    super().init_process()
  File "/www/wwwroot/AMEN-GoEdge-User_backEnd-master/af051c89597cd018ce51bd8fd53014ff_venv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/www/wwwroot/AMEN-GoEdge-User_backEnd-master/af051c89597cd018ce51bd8fd53014ff_venv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/www/wwwroot/AMEN-GoEdge-User_backEnd-master/af051c89597cd018ce51bd8fd53014ff_venv/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/www/wwwroot/AMEN-GoEdge-User_backEnd-master/af051c89597cd018ce51bd8fd53014ff_venv/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/www/wwwroot/AMEN-GoEdge-User_backEnd-master/af051c89597cd018ce51bd8fd53014ff_venv/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/www/wwwroot/AMEN-GoEdge-User_backEnd-master/af051c89597cd018ce51bd8fd53014ff_venv/lib/python3.7/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
  File "/www/wwwroot/AMEN-GoEdge-User_backEnd-master/af051c89597cd018ce51bd8fd53014ff_venv/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/www/wwwroot/AMEN-GoEdge-User_backEnd-master/main.py", line 6, in <module>
    import requests
  File "/www/wwwroot/AMEN-GoEdge-User_backEnd-master/af051c89597cd018ce51bd8fd53014ff_venv/lib/python3.7/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/www/wwwroot/AMEN-GoEdge-User_backEnd-master/af051c89597cd018ce51bd8fd53014ff_venv/lib/python3.7/site-packages/urllib3/__init__.py", line 42, in <module>
    "urllib3 v2.0 only supports OpenSSL 1.1.1+, currently "
ImportError: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'OpenSSL 1.0.2k-fips  26 Jan 2017'. See: https://github.com/urllib3/urllib3/issues/2168
[2023-11-18 09:35:11 +0000] [15842] [INFO] Worker exiting (pid: 15842)
[2023-11-18 09:35:11 +0000] [15834] [ERROR] Worker (pid:15842) exited with code 3
[2023-11-18 09:35:11 +0000] [15834] [ERROR] Shutting down: Master
[2023-11-18 09:35:11 +0000] [15834] [ERROR] Reason: Worker failed to boot.
[2023-11-18 09:36:23 +0000] [16809] [INFO] Starting gunicorn 21.2.0
[2023-11-18 09:36:23 +0000] [16809] [INFO] Listening at: http://0.0.0.0:80 (16809)
[2023-11-18 09:36:23 +0000] [16809] [INFO] Using worker: geventwebsocket.gunicorn.workers.GeventWebSocketWorker
[2023-11-18 09:36:23 +0000] [16817] [INFO] Booting worker with pid: 16817
[2023-11-18 09:36:24 +0000] [16817] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/www/wwwroot/AMEN-GoEdge-User_backEnd-master/af051c89597cd018ce51bd8fd53014ff_venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/www/wwwroot/AMEN-GoEdge-User_backEnd-master/af051c89597cd018ce51bd8fd53014ff_venv/lib/python3.7/site-packages/gunicorn/workers/ggevent.py", line 147, in init_process
    super().init_process()
  File "/www/wwwroot/AMEN-GoEdge-User_backEnd-master/af051c89597cd018ce51bd8fd53014ff_venv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/www/wwwroot/AMEN-GoEdge-User_backEnd-master/af051c89597cd018ce51bd8fd53014ff_venv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/www/wwwroot/AMEN-GoEdge-User_backEnd-master/af051c89597cd018ce51bd8fd53014ff_venv/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/www/wwwroot/AMEN-GoEdge-User_backEnd-master/af051c89597cd018ce51bd8fd53014ff_venv/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/www/wwwroot/AMEN-GoEdge-User_backEnd-master/af051c89597cd018ce51bd8fd53014ff_venv/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/www/wwwroot/AMEN-GoEdge-User_backEnd-master/af051c89597cd018ce51bd8fd53014ff_venv/lib/python3.7/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
  File "/www/wwwroot/AMEN-GoEdge-User_backEnd-master/af051c89597cd018ce51bd8fd53014ff_venv/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/www/wwwroot/AMEN-GoEdge-User_backEnd-master/main.py", line 6, in <module>
    import requests
  File "/www/wwwroot/AMEN-GoEdge-User_backEnd-master/af051c89597cd018ce51bd8fd53014ff_venv/lib/python3.7/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/www/wwwroot/AMEN-GoEdge-User_backEnd-master/af051c89597cd018ce51bd8fd53014ff_venv/lib/python3.7/site-packages/urllib3/__init__.py", line 42, in <module>
    "urllib3 v2.0 only supports OpenSSL 1.1.1+, currently "
ImportError: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'OpenSSL 1.0.2k-fips  26 Jan 2017'. See: https://github.com/urllib3/urllib3/issues/2168
[2023-11-18 09:36:24 +0000] [16817] [INFO] Worker exiting (pid: 16817)
[2023-11-18 09:36:24 +0000] [16809] [ERROR] Worker (pid:16817) exited with code 3
[2023-11-18 09:36:24 +0000] [16809] [ERROR] Shutting down: Master
[2023-11-18 09:36:24 +0000] [16809] [ERROR] Reason: Worker failed to boot.
[2023-11-18 09:57:19 +0000] [19721] [INFO] Starting gunicorn 21.2.0
[2023-11-18 09:57:19 +0000] [19721] [INFO] Listening at: http://0.0.0.0:80 (19721)
[2023-11-18 09:57:19 +0000] [19721] [INFO] Using worker: geventwebsocket.gunicorn.workers.GeventWebSocketWorker
[2023-11-18 09:57:19 +0000] [19729] [INFO] Booting worker with pid: 19729
[2023-11-18 09:57:20 +0000] [19729] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/www/wwwroot/AMEN-GoEdge-User_backEnd-master/af051c89597cd018ce51bd8fd53014ff_venv/lib/python3.7/site-packages/pydantic/type_adapter.py", line 197, in __init__
    validator = _getattr_no_parents(type, '__pydantic_validator__')
  File "/www/wwwroot/AMEN-GoEdge-User_backEnd-master/af051c89597cd018ce51bd8fd53014ff_venv/lib/python3.7/site-packages/pydantic/type_adapter.py", line 98, in _getattr_no_parents
    raise AttributeError(attribute)
AttributeError: __pydantic_validator__

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/www/wwwroot/AMEN-GoEdge-User_backEnd-master/af051c89597cd018ce51bd8fd53014ff_venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/www/wwwroot/AMEN-GoEdge-User_backEnd-master/af051c89597cd018ce51bd8fd53014ff_venv/lib/python3.7/site-packages/gunicorn/workers/ggevent.py", line 147, in init_process
    super().init_process()
  File "/www/wwwroot/AMEN-GoEdge-User_backEnd-master/af051c89597cd018ce51bd8fd53014ff_venv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/www/wwwroot/AMEN-GoEdge-User_backEnd-master/af051c89597cd018ce51bd8fd53014ff_venv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/www/wwwroot/AMEN-GoEdge-User_backEnd-master/af051c89597cd018ce51bd8fd53014ff_venv/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/www/wwwroot/AMEN-GoEdge-User_backEnd-master/af051c89597cd018ce51bd8fd53014ff_venv/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/www/wwwroot/AMEN-GoEdge-User_backEnd-master/af051c89597cd018ce51bd8fd53014ff_venv/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/www/wwwroot/AMEN-GoEdge-User_backEnd-master/af051c89597cd018ce51bd8fd53014ff_venv/lib/python3.7/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
  File "/www/wwwroot/AMEN-GoEdge-User_backEnd-master/af051c89597cd018ce51bd8fd53014ff_venv/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/www/wwwroot/AMEN-GoEdge-User_backEnd-master/main.py", line 12, in <module>
    from Controller.UserService import app as UserService
  File "/www/wwwroot/AMEN-GoEdge-User_backEnd-master/Controller/UserService.py", line 32, in <module>
    commons: dict = Depends(Utils.init)):
  File "/www/wwwroot/AMEN-GoEdge-User_backEnd-master/af051c89597cd018ce51bd8fd53014ff_venv/lib/python3.7/site-packages/fastapi/routing.py", line 729, in decorator
    generate_unique_id_function=generate_unique_id_function,
  File "/www/wwwroot/AMEN-GoEdge-User_backEnd-master/af051c89597cd018ce51bd8fd53014ff_venv/lib/python3.7/site-packages/fastapi/routing.py", line 669, in add_api_route
    generate_unique_id_function=current_generate_unique_id,
  File "/www/wwwroot/AMEN-GoEdge-User_backEnd-master/af051c89597cd018ce51bd8fd53014ff_venv/lib/python3.7/site-packages/fastapi/routing.py", line 489, in __init__
    self.dependant = get_dependant(path=self.path_format, call=self.endpoint)
  File "/www/wwwroot/AMEN-GoEdge-User_backEnd-master/af051c89597cd018ce51bd8fd53014ff_venv/lib/python3.7/site-packages/fastapi/dependencies/utils.py", line 265, in get_dependant
    is_path_param=is_path_param,
  File "/www/wwwroot/AMEN-GoEdge-User_backEnd-master/af051c89597cd018ce51bd8fd53014ff_venv/lib/python3.7/site-packages/fastapi/dependencies/utils.py", line 435, in analyze_param
    field_info=field_info,
  File "/www/wwwroot/AMEN-GoEdge-User_backEnd-master/af051c89597cd018ce51bd8fd53014ff_venv/lib/python3.7/site-packages/fastapi/utils.py", line 99, in create_response_field
    return ModelField(**kwargs)  # type: ignore[arg-type]
  File "<string>", line 6, in __init__
  File "/www/wwwroot/AMEN-GoEdge-User_backEnd-master/af051c89597cd018ce51bd8fd53014ff_venv/lib/python3.7/site-packages/fastapi/_compat.py", line 108, in __post_init__
    Annotated[self.field_info.annotation, self.field_info]
  File "/www/wwwroot/AMEN-GoEdge-User_backEnd-master/af051c89597cd018ce51bd8fd53014ff_venv/lib/python3.7/site-packages/pydantic/type_adapter.py", line 203, in __init__
    core_schema, type, module, str(type), 'TypeAdapter', core_config, config_wrapper.plugin_settings
  File "/www/wwwroot/AMEN-GoEdge-User_backEnd-master/af051c89597cd018ce51bd8fd53014ff_venv/lib/python3.7/site-packages/pydantic/plugin/_schema_validator.py", line 49, in create_schema_validator
    return SchemaValidator(schema, config)
pydantic_core._pydantic_core.SchemaError: Error building "str" validator:
  SchemaError: regex parse error:
    ^(?:(?=.*[A-Z])(?=.*[a-z])(?=.*[0-9])).*$
        ^^^
error: look-around, including look-ahead and look-behind, is not supported
[2023-11-18 09:57:20 +0000] [19729] [INFO] Worker exiting (pid: 19729)
[2023-11-18 09:57:20 +0000] [19721] [ERROR] Worker (pid:19729) exited with code 3
[2023-11-18 09:57:20 +0000] [19721] [ERROR] Shutting down: Master
[2023-11-18 09:57:20 +0000] [19721] [ERROR] Reason: Worker failed to boot.
[2023-11-18 09:59:41 +0000] [20094] [INFO] Starting gunicorn 21.2.0
[2023-11-18 09:59:41 +0000] [20094] [INFO] Listening at: http://0.0.0.0:80 (20094)
[2023-11-18 09:59:41 +0000] [20094] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2023-11-18 09:59:41 +0000] [20102] [INFO] Booting worker with pid: 20102
[2023-11-18 09:59:42 +0000] [20102] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/www/wwwroot/AMEN-GoEdge-User_backEnd-master/af051c89597cd018ce51bd8fd53014ff_venv/lib/python3.7/site-packages/pydantic/type_adapter.py", line 197, in __init__
    validator = _getattr_no_parents(type, '__pydantic_validator__')
  File "/www/wwwroot/AMEN-GoEdge-User_backEnd-master/af051c89597cd018ce51bd8fd53014ff_venv/lib/python3.7/site-packages/pydantic/type_adapter.py", line 98, in _getattr_no_parents
    raise AttributeError(attribute)
AttributeError: __pydantic_validator__

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/www/wwwroot/AMEN-GoEdge-User_backEnd-master/af051c89597cd018ce51bd8fd53014ff_venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/www/wwwroot/AMEN-GoEdge-User_backEnd-master/af051c89597cd018ce51bd8fd53014ff_venv/lib/python3.7/site-packages/uvicorn/workers.py", line 66, in init_process
    super(UvicornWorker, self).init_process()
  File "/www/wwwroot/AMEN-GoEdge-User_backEnd-master/af051c89597cd018ce51bd8fd53014ff_venv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/www/wwwroot/AMEN-GoEdge-User_backEnd-master/af051c89597cd018ce51bd8fd53014ff_venv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/www/wwwroot/AMEN-GoEdge-User_backEnd-master/af051c89597cd018ce51bd8fd53014ff_venv/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/www/wwwroot/AMEN-GoEdge-User_backEnd-master/af051c89597cd018ce51bd8fd53014ff_venv/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/www/wwwroot/AMEN-GoEdge-User_backEnd-master/af051c89597cd018ce51bd8fd53014ff_venv/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/www/wwwroot/AMEN-GoEdge-User_backEnd-master/af051c89597cd018ce51bd8fd53014ff_venv/lib/python3.7/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
  File "/www/wwwroot/AMEN-GoEdge-User_backEnd-master/af051c89597cd018ce51bd8fd53014ff_venv/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/www/wwwroot/AMEN-GoEdge-User_backEnd-master/main.py", line 12, in <module>
    from Controller.UserService import app as UserService
  File "/www/wwwroot/AMEN-GoEdge-User_backEnd-master/Controller/UserService.py", line 32, in <module>
    commons: dict = Depends(Utils.init)):
  File "/www/wwwroot/AMEN-GoEdge-User_backEnd-master/af051c89597cd018ce51bd8fd53014ff_venv/lib/python3.7/site-packages/fastapi/routing.py", line 729, in decorator
    generate_unique_id_function=generate_unique_id_function,
  File "/www/wwwroot/AMEN-GoEdge-User_backEnd-master/af051c89597cd018ce51bd8fd53014ff_venv/lib/python3.7/site-packages/fastapi/routing.py", line 669, in add_api_route
    generate_unique_id_function=current_generate_unique_id,
  File "/www/wwwroot/AMEN-GoEdge-User_backEnd-master/af051c89597cd018ce51bd8fd53014ff_venv/lib/python3.7/site-packages/fastapi/routing.py", line 489, in __init__
    self.dependant = get_dependant(path=self.path_format, call=self.endpoint)
  File "/www/wwwroot/AMEN-GoEdge-User_backEnd-master/af051c89597cd018ce51bd8fd53014ff_venv/lib/python3.7/site-packages/fastapi/dependencies/utils.py", line 265, in get_dependant
    is_path_param=is_path_param,
  File "/www/wwwroot/AMEN-GoEdge-User_backEnd-master/af051c89597cd018ce51bd8fd53014ff_venv/lib/python3.7/site-packages/fastapi/dependencies/utils.py", line 435, in analyze_param
    field_info=field_info,
  File "/www/wwwroot/AMEN-GoEdge-User_backEnd-master/af051c89597cd018ce51bd8fd53014ff_venv/lib/python3.7/site-packages/fastapi/utils.py", line 99, in create_response_field
    return ModelField(**kwargs)  # type: ignore[arg-type]
  File "<string>", line 6, in __init__
  File "/www/wwwroot/AMEN-GoEdge-User_backEnd-master/af051c89597cd018ce51bd8fd53014ff_venv/lib/python3.7/site-packages/fastapi/_compat.py", line 108, in __post_init__
    Annotated[self.field_info.annotation, self.field_info]
  File "/www/wwwroot/AMEN-GoEdge-User_backEnd-master/af051c89597cd018ce51bd8fd53014ff_venv/lib/python3.7/site-packages/pydantic/type_adapter.py", line 203, in __init__
    core_schema, type, module, str(type), 'TypeAdapter', core_config, config_wrapper.plugin_settings
  File "/www/wwwroot/AMEN-GoEdge-User_backEnd-master/af051c89597cd018ce51bd8fd53014ff_venv/lib/python3.7/site-packages/pydantic/plugin/_schema_validator.py", line 49, in create_schema_validator
    return SchemaValidator(schema, config)
pydantic_core._pydantic_core.SchemaError: Error building "str" validator:
  SchemaError: regex parse error:
    ^(?:(?=.*[A-Z])(?=.*[a-z])(?=.*[0-9])).*$
        ^^^
error: look-around, including look-ahead and look-behind, is not supported
[2023-11-18 09:59:42 +0000] [20102] [INFO] Worker exiting (pid: 20102)
[2023-11-18 09:59:42 +0000] [20094] [ERROR] Worker (pid:20102) exited with code 3
[2023-11-18 09:59:42 +0000] [20094] [ERROR] Shutting down: Master
[2023-11-18 09:59:42 +0000] [20094] [ERROR] Reason: Worker failed to boot.

```

**Comment by skyhhjmk** [comment]
![image](https://github.com/2331892928/AMEN-GoEdge-User_backEnd/assets/78078552/55ee62ef-3eb3-4e12-a846-68deea3ce863)

**Comment by skyhhjmk** [comment]
解决了，把fastapi降级即可
